version: '3.7'
services:
  ##################################################################
  robot:
    build:
      context: ./robot
    shm_size: '2gb'
    volumes:
      - ./robot/fixtures:/opt/robotframework/fixtures:Z
      - ./robot/libraries:/opt/robotframework/libraries:Z
      - ./robot/listeners:/opt/robotframework/listeners:Z
      - ./robot/reports:/opt/robotframework/reports:Z
      - ./robot/test:/opt/robotframework/test:Z
      - ./robot/testLauncher:/opt/robotframework/testLauncher:Z

    environment:
      # All env vars documented in README.md
      BASE_URL: https://bwillenbring1.shotgunstudio.com
      BROWSER: chrome
      USERNAME:
      PASSWORD:
      TEST_PROJECT_ID: "${TEST_PROJECT_ID}"
      ROBOT_LISTENER: /opt/robotframework/listeners/CustomListener.py
      ROBOT_OUTPUTDIR: /opt/robotframework/reports
      ROBOT_SPECS: /opt/robotframework/test
    command: python testLauncher/testLauncher.py
  ###
  cypress:
    build:
      context: ./cypress
    volumes:
        - ./cypress:/mnt/cypress
    # Run the cypress command
    command: bash -c "
        echo --------------------
        && echo npm modules...
        && printf '\n'
        && npm ls
        && echo --------------------
        && echo Node Version...
        && node -v
        && printf '\n'
        && echo 'npm version...'
        && npm -v
        && echo --------------------
        && echo Environment variables...
        && printenv
        && echo --------------------
        && echo Contents of /mnt/cypress...
        && ls /mnt/cypress
        && echo --------------------
        && echo Running run.js...
        && printf '\n'
        && node run.js
        "
