name: Cron Jobs

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ls txt files
      run: |
        touch ls.txt
        ls *.txt

    - name: echo github vars
      run: |
        echo github.event
        echo github.repository
        echo github.actor
        echo github.sha
        echo github.ref
        echo github.actor
