name: Run Tests

on: [push]

jobs:
  set_shared_env_vars:
    name: Set Shared Environment Variables
    runs-on: ubuntu-latest
    env:
        SURPRISE: From a different job!!!
        BASE_URL: ${{ secrets.SG_BASE_URL }}
        BROWSER: ${{ secrets.SG_BROWSER }}
        USERNAME: ${{ secrets.SG_USERNAME }}
        PASSWORD: ${{ secrets.SG_PASSWORD }}

    steps:
      - name: First Step => Checkout
        uses: actions/checkout@v1

      - name: 2nd Step
        uses: actions/setup-python@v1
        with:
          python-version: 2.7

      - name: Install Python and create Test Project
        run: |
          python -m pip install --upgrade pip
          pip install -r robot/requirements.txt
          export TEST_PROJECT_ID2=$(python robot/testLauncher/create_test_project.py)
          echo "Created Test Project $TEST_PROJECT_ID2"
          echo Saving to shared_artifacts
          mkdir -p shared_artifacts
          echo $TEST_PROJECT_ID2 > shared_artifacts/TEST_PROJECT_ID.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: shared_artifacts

  cypress:
    name: Cypress
    runs-on: ubuntu-latest
    needs: set_shared_env_vars
    env:
        BASE_URL: ${{ secrets.SG_BASE_URL }}
        BROWSER: ${{ secrets.SG_BROWSER }}
        USERNAME: ${{ secrets.SG_USERNAME }}
        PASSWORD: ${{ secrets.SG_PASSWORD }}
        TEST_PROJECT_ID: 66

    steps:
      - name: First Step => Checkout
        uses: actions/checkout@v1

      - name: Download Artifacts from Step 1
        uses: actions/download-artifact@v1
        with:
          name: my-artifact
          path: shared_artifacts

      - name: Confirm Downloaded Artifacts
        run: |
          echo Running ls on shared_artifacts dir
          ls shared_artifacts
          cat shared_artifacts/TEST_PROJECT_ID.txt

      - name: Build the Cypress Docker Container
        run: |
          echo echoing surpirse...
          echo $SURPRISE
          docker-compose build cypress

      - name: Up the Cypress Container
        env:
          BASE_URL: ${{ secrets.SG_BASE_URL }}
          BROWSER: ${{ secrets.SG_BROWSER }}
          USERNAME: ${{ secrets.SG_USERNAME }}
          PASSWORD: ${{ secrets.SG_PASSWORD }}
          TEST_PROJECT_ID: 66
        run: |
          python cypress/testLauncher/testLauncher.py
          docker-compose up cypress

      - name: Move Cypress assets to mochawesome-report dir
        run: |
          cp -r cypress/videos cypress/mochawesome-report

      - name: Publish Cypress assets to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'cypress/mochawesome-report'
          DEST_DIR: 'cypress'

  robot:
    name: Robot & Selenium Stage
    needs: set_shared_env_vars
    runs-on: ubuntu-latest
    env:
        BASE_URL: ${{ secrets.SG_BASE_URL }}
        BROWSER: ${{ secrets.SG_BROWSER }}
        USERNAME: ${{ secrets.SG_USERNAME }}
        PASSWORD: ${{ secrets.SG_PASSWORD }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install python dependencies
      run: |
        echo echoing surpirse...
        echo $SURPRISE
        python -m pip install --upgrade pip
        pip install -r robot/requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Robot Specs in Docker Container
      run: |
        export TEST_PROJECT_ID=$(python robot/testLauncher/create_test_project.py)
        echo "Created Test Project $TEST_PROJECT_ID"
        printenv
        robot --outputdir robot/reports robot/test/simple-variables.robot
        echo "Building the docker image..."
        docker-compose up --build robot
        echo "DONE!"
    - name: Publish assets to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: 'robot/reports'
        DEST_DIR: 'robot'
